**Feature Engineering**  
Date Created: 4/2/2020  
Last Edited: 4/2/2020  
Description: Feature engineer a dataset. Specifically feature scaling, identification of noise/outliers, mitigating class imbalance (perhapse through SMOTE), feature selection (Wrapper Methods) and feature extraction (PCA, SVD and LDA)

In [1]:
#Load Libraries
import pandas as pd
import numpy as np

In [12]:
#Load dataset
data = pd.read_csv("data_test_interpolate.csv")
data_X = data.iloc[:, 1:21] #df with featues
data_Y = data.iloc[:, 21:] #df with class labels
print(data_Y.head(10))
data_X.head(10)

   death = 1
0           1
1           1
2           1
3           1
4           1
5           1
6           1
7           1
8           0
9           1

,age,sex,Alb,PLT,WBC,CRP,APACHE II,SOFA,McCabe,PaO2/FiO2,LDH,CT score,PEEP,PIP,TV,DARDS = 1,days,days.1,ventilator weaning = 1,VFD
0,79,M,2.3,10.8,4000,17.8,24,8,1,108.0,339,191.6,24,22,420,0,21,28,0,0
1,83,M,4.4,13.5,10200,8.9,16,6,1,78.0,385,213.3,5,10,360,0,21,28,0,0
2,70,M,2.7,10.8,5300,25.3,22,7,1,70.9,461,221.7,18,24,525,0,8,28,0,0
3,61,M,3.3,8.8,1800,22.2,26,7,1,59.2,227,211.6,10,24,480,0,11,28,0,0
4,81,M,3.1,26.2,10600,17.0,19,4,1,83.6,680,234.9,5,10,625,0,6,28,0,0
5,79,M,3.4,37.9,13200,21.0,18,5,1,71.5,224,236.7,5,25,460,0,12,28,0,0
6,83,M,2.8,18.0,1500,54.9,30,11,1,96.2,342,180.5,22,22,420,0,1,28,0,0
7,70,M,2.8,18.5,14100,18.4,15,5,1,78.2,478,311.6,10,25,420,0,13,28,0,0
8,65,F,3.2,35.4,7200,10.4,18,3,1,194.0,316,231.6,8,23,440,0,28,10,1,18
9,72,M,2.9,26.8,19800,29.4,20,5,1,74.0,245,233.1,5,25,420,0,22,16,1,12

In [17]:
#Class Imbalance
#Dependencies on imblearn and joblib
#conda install -c conda-forge imbalanced-learn
#conda install -c anaconda joblib
#SMOTE
import imblearn